# Generated by Django 2.2.9 on 2022-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220422_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Max 200 characters', max_length=200, verbose_name='Title'),
        ),
    ]
