# Generated by Django 2.2.19 on 2022-05-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
